### ISSUE TITLE
kops example fails

### ISSUE THREAD

**Issue by chrislovecnm** [romana/romana#144]
Using this:

`
https://github.com/romana/romana/tree/master/containerize#using-kops
`

Currently, fails.  Please see:

https://github.com/kubernetes/kops/issues/877

**Comment by cgilmour** [comment]
Hi @chrislovecnm , thanks for opening an issue.

I'll have a look and make some updates.
There's a small issue with policy agent that has been fixed and will be released soon.
I also need to document an additional step for EC2 instances - disabling source-dest-check.
However, from the referenced issue, it seems that the policy agent was not running. I'll see if I can reproduce that.

**Comment by chrislovecnm** [comment]
@cgilmour thanks ... let me know.  Please reach out on slack, as my github messaging is a waste land

**Comment by cgilmour** [comment]
Hi @chrislovecnm, we've released an update, and it's also been tested with the 'private topology' option for kops.
Everything seemed to work as expected.
As an additional test, I installed the dashboard add-on.

I've added some additional documentation about limitations compared to kops defaults.
Some will be fixed in the near future.
The specific item about "Source Dest Check" may need changes in kops. (This will probably affect other CNI providers also.)

**Comment by chrislovecnm** [comment]
Source Dest Check not sure what you mean.  Need more details :)

**Comment by chrismarino** [comment]
from https://github.com/romana/romana/tree/master/containerize#limitations

EC2 Source Dest Check: By default, AWS EC2 instances have SourceDestCheck enabled. This needs to be disabled for pods on different hosts to communicate using their podIP addresses.

**Comment by chrislovecnm** [comment]
What is the status on this?

**Comment by chrismarino** [comment]
Hey, @chrislovecnm  ......I think this specific issue has been resolved.
