### ISSUE TITLE
Romana + Kubernetes behind the NAT

### ISSUE THREAD

**Issue by zreigz** [romana/romana#158]
According to this document http://romana.io/faq/#how-does-romana-handle-nat 
it possible to use romana behind the NAT. Can someone explain how to exactly achieve this together with kubernetes ? 
Thanks in advance

**Comment by chrismarino** [comment]
Hi @zreigz, this question in the FAQ is a bit misleading. It was included in the list because when using Romana in an OpenStack environment, NAT on a Neutron router was not supported. The point being that since NAT was unavailable there, it needed to be provided some place else. 

As for your specific question about deploying Romana with k8s behind NAT, I'm not sure I completely understand. Kubernetes does perform NAT from the pod network to external networks via kube-proxy and ClusterIPs so Romana doesn't need to do anything special. 

Can you provide more detail on your use case? Also, I send you an invite to our Slack channel if you want a live response.

**Comment by zreigz** [comment]
I have installed k8s master on gce, so it is available with some external IP. Now I would like be able to connect minions from any places (different locations, networks). For instance when I create my minion in my local home network then I have two problems. First when I execute `kubectl logs` or `kubectl exec` then master initialize connection to node. Because node is located in my local network so there to chance to reach it. Second problem is with flannel overlay because it works for the same network.

Only idea which comes to my mind is using VPN between minion and master. I've experimenting also with tun/tap interface to be able create lightweight VPN.

**Comment by chrismarino** [comment]
OK. I see. This kind of deployment presents a bunch of problems because the nodes are not directly reachable without NAT. I think you're going to have to build a mesh VPN among the nodes. Romana isn't going to help with that at all. Depending on how you build the mesh (i.e. tun vs. tap) you'll have either L2 or L3 connectivity across the VPN.  I think both flannel and Romana will work on the VPN, but you may also need to add routes to get to the pod network (similar to the way AWS needs VPC routes between subnets).

A VPN mesh is not something we've tried ourselves, so not sure how helpful we can be...

**Comment by zreigz** [comment]
OK, thanks for explanation and your time. I think I can close the issue
