### ISSUE TITLE
Can not start romana-agent on k8s

### ISSUE THREAD

**Issue by shafreeck** [romana/romana#167]
I installed k8s cluster from scratch followed the guides of k8s docs. But I can not deploy romana with the file romana-kubeadm.yml.

```
[root@centos1 ~]# kubectl -n kube-system get pod
NAME                               READY     STATUS             RESTARTS   AGE
etcd-server-kube-centos1           1/1       Running            7          42m
kube-apiserver-centos1             1/1       Running            3          42m
kube-controller-manager-centos1    1/1       Running            7          42m
kube-scheduler-centos1             1/1       Running            8          41m
romana-agent-ggjwj                 0/1       CrashLoopBackOff   4          4m
romana-services-1301461361-l7ck0   3/3       Running
```

And I got the logs

```
[root@centos1 ~]# kubectl -n kube-system logs romana-agent-ggjwj
Checking topology service is available from romanaok
Internal Error: no host information found
```

It really stuck me here.  Looking forward to help!

**Comment by shafreeck** [comment]
I solved it by myself. I missed the argument '--pod-to-host'. Maybe you should document it clearly.

**Comment by cgilmour** [comment]
Hi @shafreeck , thanks for trying Romana and sorry to hear you got stuck.

I think the cause is unrelated to the `pod-to-host` option, which defaults to `true`.
However, changing the config and re-applying it will have cleared the CrashLoopBackOff delay timer.
I suspect that the romana-services containers took a while to get pulled and launch the components inside it, so romana-agent pod was having trouble connecting to it and exiting after a timeout. That put it into CrashLoopBackoff, but it should have recovered from that a moment or two later, once the romana-services pod was fully initialized.

If you have further trouble or just questions/comments, please reach out to us again.
