### ISSUE TITLE
Multiple IP addresses per host

### ISSUE THREAD

**Issue by ymmt2005** [romana/romana#179]
Problem:
We want to have ECMP routes between nodes in the same L2 domain.
Current agent implementation does not setup ECMP as it assumes each
Host has only one IP address.

Background:
We have two ToR switches in a rack.  Each ToR provides distinct L2 domains,
therefore distinct subnet IP addresses, to servers with 2 NIC ports.

This way, each server has two equal-cost IP addresses.  Default route
is set up with the two paths using ECMP like:
```
$ ip route show 0.0.0.0/0
default  metric 2 
        nexthop via 10.0.1.1  dev eno1 weight 1
        nexthop via 10.1.0.1  dev eno2 weight 1
```
where `eno1` connects to ToR switch 1 and `eno2` to ToR 2.

This setup mostly works nicely with Romana, except for routes to nodes
in the same L2 domain.  Romana agent automatically setup routes to
address blocks like this:
```
$ ip route show table 10
192.168.0.0/29 via 10.0.1.2 dev eno1
192.168.0.16/29 via 10.0.1.5 dev eno1
192.168.128.0/29 via 10.0.1.8 dev eno1
```

Question:
Can we configure Romana to setup ECMP routes for this case?
If not, any future plan to support this?

For your reference, Kubernetes allows a Node to have multiple addresses.
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.9/#nodestatus-v1-core

Thank you!

**Comment by chrismarino** [comment]
Hi @ymmt2005 Lots going on here. Some questions though.  When you say ECMP, do mean ECMP for both egress and ingress traffic? Or do you just want each subnet to use its own NIC? That is, each subnet to have a different default route? From your example, I'm guessing that you've got two /17 networks (196.168.0.0/17 and 192.168.128.0/17). So, if the .128.0 network gets set with a different default route to eno2, this would put egress traffic up to the other ToR.

> $ ip route show table 10
> 192.168.0.0/29 via 10.0.1.2 dev eno1
> 192.168.0.16/29 via 10.0.1.5 dev eno1
> 192.168.128.0/29 via 10.0.1.8 dev eno2

This isn't ECMP for egress traffic, but does split the traffic across the NICs. ECMP for ingress traffic needs to be handled on the  ToRs (or on the upstream L3 device if the ToRs are just L2 devices).

Either way, there are several possibilities, not exactly sure of the status/details of any of them, but let me describe them.  The interface for the default route is set during installation and there is some automated mechanism to detect what interfaces are available and one is chosen.  I don't think the installer can handles multiple subnets, but it might be possible to do something manually to set it up this way. @cgilmour would have more info on how to get that to work. It is also possible that the network topology configuration will accept an interface specification. I know we talked about this, but not sure if it has been implemented. Would need @jbrendel to clarify the status of this.

If you are looking for ECMP for ingress traffic, that needs to be configured on upstream devices. This will require the [route publisher add on](http://docs.romana.io/Content/advanced.html#route-publisher-add-on).   And using the route publisher for ECMP on multiple NICs is going to require a customer Bird configuration. But more importantly, the  nodes need to peer with the upstream router, and not clear from your description if these are the ToRs, of if there is an L3 device further upstream.

As for CNI supporting multiple IPs, yes, that is true, but don't think the Romana CNI implementation handles that automatically (which is why you might have to do a custom install).

Are you already using the route publisher to set up L3 network zones for HA? Or do you use the redundant L2 ToRs for HA?

**Comment by chrismarino** [comment]
Forgot to mention that it might also be possible to configure the route publisher to handle this even with default routes set to eno1. Not the Bird expert, would need @flashvoid to clarify what might be possible.

**Comment by ymmt2005** [comment]
@chrismarino 
Thank you for the detailed reply.  Yes, we want ECMP for egress.

Upstream routers are responsible for ingress and we can do it thanks to
the highly configurable route publisher (in fact, it is one of the greatest
strength of Romana, I think!).

The problem here is not only to distribute egress loads, but also to keep
redundant routes in preparation for ToR failure.

We are thinking that one possible workaround might be to remove routes
inserted by Romana agent and leave all egress to the default gateway
which we configure manually as ECMP routes.

This will work for us because ToR knows every routes in the rack thanks to
the route publisher add-on.  Such ToR will return ICMP redirect to the
node having the destination addresses, hence Romana network remain
working.

If Romana can disable automatic routing in the same L2 domain, we will
try it and see whether the above scenario succeeds or not.  Or we can disable
it manually by removing rule 32765 from `ip rule`, right?

```
$ ip rule
0:      from all lookup local 
32765:  from all lookup 10 
32766:  from all lookup main 
32767:  from all lookup default 
```

Many thanks to your kind advice!

**Comment by chrismarino** [comment]
OK. @ymmt2005 I understand. Looks like you're already using the route publisher add on for upstream route distribution. I think your workaround will work as well. But not the expert on how Romana will behave if the routes/rules are deleted. The agent might try to re-install them...

I'm pretty sure the Romana agent installs routes even if they are not necessary because the route publisher is used. And I don't think this can be disabled. In most cases they don't harm anything, but for your scenario they actually prevent the ECMP behavior you're looking for. 

Will have to hear back from the rest of the team to fully understand what the various alternatives are and how they behave, but I think deleting the rules should work.

Give it a try and let me know.

**Comment by ymmt2005** [comment]
We will try.  Please expect this will take a while.

**Comment by cgilmour** [comment]
The agent creates the rule for `table 10` when it launches. So if it were deleted manually then the agent restarted, it will get recreated.
There's no option for disabling the rule and route management in the agent at the moment.
If it's helpful to have an option for this, we can consider it.

I think Kubernetes will limit things to a single InternalIP per node. If so, even if Romana supported ECMP or left that to the underlying hosts, a ToR failure could still affect the Kubernetes control plane.
It'd be good to check this and report if it was OK or not in this circumstance.

**Comment by ymmt2005** [comment]
@cgilmour Thank you.  We will check how k8s works in case of a ToR failure.

**Comment by flashvoid** [comment]
@ymmt2005 I made a container for you that supports disabling route management - try `quay.io/romana/agent:hotfix-291` with the environment variable `EXPERIMENT_MANAGE_ROUTES=false` pushed into a container.

Supporting ECMP how you proposed in the issue is interesting and not very hard to do, but I don't know what would be the best way to express such configuration.

**Comment by ymmt2005** [comment]
@flashvoid Wow, thank you!

**Comment by ymmt2005** [comment]
We finally decided to have a single authoritative address for each node.
Thank you very much for all of your kind help!
