### ISSUE TITLE
Is there a manual install instruction?

### ISSUE THREAD

**Issue by tweakmy** [romana/romana#92]
Hi there,

Is there  a similar thing like http://kubernetes.io/docs/getting-started-guides/ubuntu-calico/ version of romana?  Understand there is a vagrant ansible which simplify the installation. However, I am using kvm. And I have to learn all the new tricks on ansible? Is there a simplified version?

Thanks.

**Comment by jbrendel** [comment]
Hello!

We are still working on that document for Romana and are not quite finished, yet.

In the meantime, however, we are also modifying our installation scripts so that you do not need to use Vagrant, but instead can point at already existing VMs or even hardware boxes. Maybe this might be a useful compromise? You could create some VMs via kvm and then let our installer configure a cluster on those machines for you. It would do this via Ansible, but you don't need to learn Ansible, since it would be driven by a convenient wrapper script.

Would this work for you?

Juergen

**Comment by tweakmy** [comment]
I think for a fast start, a script should be sufficient for me as long I don't have to keep up with a lot of new technologies. 
As an overall or for any romana newbie,would appreciate if we know where the components are install and if the components does terminate(due to error etc), then it is much easier to troubleshoot or raise an issue or pr? Just a thought.

**Comment by amon-ra** [comment]
Calico provides a docker image. This is ideal in my opinion

**Comment by jbrendel** [comment]
The docker-image approach is something we are also experimenting with. Having it will be great for those who quickly wish to try out Romana. We do hope that the current installer - with the option to install against AWS, locally created VMs or static servers - covers a lot of bases and goes a long way towards making exploring Romana easy, without requiring too many prerequisites to be installed on your machine. 

Many people are interested in the details of what is needed for an installation and so a documented manual installation procedure will come soon.

**Comment by pritesh** [comment]
Fixed in https://github.com/pritesh/romana-setup
